spring.application.name=school-finance-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/school_finance_db
spring.datasource.username=postgres
spring.datasource.password=Kh@lil01
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=school_finance
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.error.include-message=always
server.error.include-binding-errors=always